#!/bin/bash
user="ubuntu"

rm -rf /home/$user/Desktop/FalseRansomwares
mkdir /home/$user/Desktop/FalseRansomwares
git clone https://github.com/billziss-gh/secfs.test.git /home/$user/Desktop/FalseRansomwares/fsrand
mv /home/$user/Desktop/FalseRansomwares/fsrand/fsrand/fsrand.py /home/$user/Desktop/FalseRansomwares/fsrand.py
rm -rf /home/$user/Desktop/FalseRansomwares/fsrand

rm -rf /home/$user/Desktop/RealRansomwares
mkdir /home/$user/Desktop/RealRansomwares
cp likeransomware.py /home/$user/Desktop/RealRansomwares