#!/usr/bin/env bash
# Parameters
testTar="/home/ohadoz/Desktop/RansomwareDetection/TestData/tar/TestData.tar.gz"
testOutput="/home/ohadoz/Desktop/RansomwareDetection/TestData/output/"
testOutputDirectory="/home/ohadoz/Desktop/RansomwareDetection/TestData/output"
buildOutput="/home/ohadoz/Desktop/RansomwareDetection/src"
sandBox="/tmp/sandbox"
testSummaryRootDirectory="/home/ohadoz/Desktop/RansomwareDetection/TestResults"
now="$(date +'%d-%m-%Y_%H-%M-%S')"
currentDate="Run_$now"
testSummaryFolder="$testSummaryRootDirectory/$currentDate"
ransomwaresListFile="/home/ohadoz/Desktop/RansomwareDetection/ransomwares"

printf "\033[1;34mConfig:\033[0m\n"
echo "Build output: $buildOutput"
echo "Test tar: $testTar"
echo "Test output: $testOutput"
echo "Sandbox: $sandBox"
sleep 5
printf "\033[1;32mOk\033[0m\n"

printf "\033[1;34mUpdating repository\033[0m\n"
git pull
sleep 5
printf "\033[1;32mOk\033[0m\n"

printf "\033[1;34mBuilding project\033[0m\n"
cd src
make
sleep 2
printf "\033[1;32mOk\033[0m\n"

printf "\033[1;34mTest data cleanup\033[0m\n"
rm -rf $testOutputDirectory
runOutput='/home/ohadoz/Desktop/RansomwareDetection/src/Run/*'
runOutput=${runOutput// /\\ }
eval rm -f ${runOutput}
sleep 2
printf "\033[1;32mOk\033[0m\n"

printf "\033[1;34mCreate test data\033[0m\n"
cd ..
mkdir $testOutput
tar -C $testOutput -zxf $testTar
sleep 2
printf "\033[1;32mOk\033[0m\n"

printf "\033[1;34mCollecting pre run data\033[0m\n"
mkdir -p $testSummaryRootDirectory
mkdir -p $testSummaryFolder
sleep 2
printf "\033[1;32mOk\033[0m\n"

printf "\033[1;34mStop previous run\033[0m\n"
sudo umount $sandBox
sleep 2
printf "\033[1;32mOk\033[0m\n"

printf "\033[1;34mStart Ransomware Detection\033[0m\n"
mkdir -p $sandBox
cd $buildOutput
./RansomwareGateway $testOutput $sandBox &
sleep 2
printf "\033[1;32mOk\033[0m\n"

printf "\033[1;34mRunning ransomwares\033[0m\n"
cd ..
while IFS= read -r ransomwarePath
do
    ransomwareName=${ransomwarePath##*/}
    echo "Running $ransomwareName"
    echo "$ransomwarePath"
done < "$ransomwaresListFile"
printf "\033[1;32mOk\033[0m\n"

printf "\033[1;34mStopping Ransomware Detection\033[0m\n"
sudo umount $sandBox
printf "\033[1;32mOk\033[0m\n"

printf "\033[1;34mChecking results\033[0m\n"
logOutput='/home/ohadoz/Desktop/RansomwareDetection/src/Run/Log*'
logOutput=${logOutput// /\\ }
eval cp $logOutput "$testSummaryFolder/log.txt"
sleep 2
printf "\033[1;32mOk\033[0m\n"

printf "\033[1;34mTest results at: $testSummaryFolder\033[0m\n"